export const chartData = [
  {
    language: 'javascript',
    item: 'bcrypt',
    breaking: '103',
    minor: '57',
    patch: '52',
    unknown: '22',
  },
  {
    language: 'javascript',
    item: 'class-transformer',
    breaking: '129',
    minor: '80',
    patch: '85',
    unknown: '60',
  },
  {
    language: 'javascript',
    item: 'class-validator',
    breaking: '23',
    minor: '48',
    patch: '73',
    unknown: '141',
  },
  {
    language: 'javascript',
    item: 'compression',
    breaking: '97',
    minor: '61',
    patch: '61',
    unknown: '137',
  },
  {
    language: 'javascript',
    item: 'config',
    breaking: '120',
    minor: '65',
    patch: '113',
    unknown: '22',
  },
  {
    language: 'javascript',
    item: 'cookie-parser',
    breaking: '139',
    minor: '68',
    patch: '106',
    unknown: '31',
  },
  {
    language: 'javascript',
    item: 'cors',
    breaking: '117',
    minor: '32',
    patch: '61',
    unknown: '47',
  },
  {
    language: 'javascript',
    item: 'cross-env',
    breaking: '42',
    minor: '17',
    patch: '143',
    unknown: '64',
  },
  {
    language: 'javascript',
    item: 'dotenv',
    breaking: '116',
    minor: '19',
    patch: '51',
    unknown: '31',
  },
  {
    language: 'javascript',
    item: 'envalid',
    breaking: '15',
    minor: '74',
    patch: '57',
    unknown: '136',
  },
  {
    language: 'javascript',
    item: 'eslint',
    breaking: '120',
    minor: '79',
    patch: '83',
    unknown: '150',
  },
  {
    language: 'javascript',
    item: 'eslint-config-prettier',
    breaking: '141',
    minor: '98',
    patch: '96',
    unknown: '112',
  },
  {
    language: 'javascript',
    item: 'eslint-plugin-prettier',
    breaking: '97',
    minor: '81',
    patch: '96',
    unknown: '99',
  },
  {
    language: 'javascript',
    item: 'express',
    breaking: '144',
    minor: '72',
    patch: '99',
    unknown: '51',
  },
  {
    language: 'javascript',
    item: 'helmet',
    breaking: '85',
    minor: '34',
    patch: '108',
    unknown: '20',
  },
  {
    language: 'javascript',
    item: 'hpp',
    breaking: '133',
    minor: '145',
    patch: '84',
    unknown: '32',
  },
  {
    language: 'javascript',
    item: 'husky',
    breaking: '24',
    minor: '101',
    patch: '104',
    unknown: '71',
  },
  {
    language: 'javascript',
    item: 'jest',
    breaking: '63',
    minor: '146',
    patch: '75',
    unknown: '50',
  },
  {
    language: 'javascript',
    item: 'jsonwebtoken',
    breaking: '97',
    minor: '121',
    patch: '56',
    unknown: '30',
  },
  {
    language: 'javascript',
    item: 'lint-staged',
    breaking: '121',
    minor: '77',
    patch: '61',
    unknown: '66',
  },
  {
    language: 'javascript',
    item: 'morgan',
    breaking: '61',
    minor: '31',
    patch: '75',
    unknown: '135',
  },
  {
    language: 'javascript',
    item: 'node-config',
    breaking: '141',
    minor: '103',
    patch: '37',
    unknown: '114',
  },
  {
    language: 'javascript',
    item: 'node-gyp',
    breaking: '72',
    minor: '122',
    patch: '117',
    unknown: '118',
  },
  {
    language: 'javascript',
    item: 'nodemon',
    breaking: '107',
    minor: '91',
    patch: '145',
    unknown: '80',
  },
  {
    language: 'javascript',
    item: 'pm2',
    breaking: '101',
    minor: '35',
    patch: '51',
    unknown: '40',
  },
  {
    language: 'javascript',
    item: 'prettier',
    breaking: '17',
    minor: '109',
    patch: '62',
    unknown: '98',
  },
  {
    language: 'javascript',
    item: 'supertest',
    breaking: '134',
    minor: '118',
    patch: '64',
    unknown: '76',
  },
  {
    language: 'javascript',
    item: 'swagger-jsdoc',
    breaking: '133',
    minor: '83',
    patch: '84',
    unknown: '77',
  },
  {
    language: 'javascript',
    item: 'swagger-ui-express',
    breaking: '143',
    minor: '69',
    patch: '108',
    unknown: '58',
  },
  {
    language: 'javascript',
    item: '@swc/cli',
    breaking: '28',
    minor: '32',
    patch: '50',
    unknown: '127',
  },
  {
    language: 'javascript',
    item: '@swc/core',
    breaking: '109',
    minor: '24',
    patch: '105',
    unknown: '107',
  },
  {
    language: 'javascript',
    item: 'tsc-alias',
    breaking: '55',
    minor: '91',
    patch: '97',
    unknown: '105',
  },
  {
    language: 'javascript',
    item: 'tsconfig-paths',
    breaking: '84',
    minor: '17',
    patch: '48',
    unknown: '27',
  },
  {
    language: 'javascript',
    item: 'ts-jest',
    breaking: '47',
    minor: '66',
    patch: '57',
    unknown: '20',
  },
  {
    language: 'javascript',
    item: 'ts-node',
    breaking: '144',
    minor: '45',
    patch: '65',
    unknown: '129',
  },
  {
    language: 'javascript',
    item: '@types/bcrypt',
    breaking: '92',
    minor: '18',
    patch: '139',
    unknown: '126',
  },
  {
    language: 'javascript',
    item: '@types/compression',
    breaking: '79',
    minor: '106',
    patch: '37',
    unknown: '28',
  },
  {
    language: 'javascript',
    item: '@types/config',
    breaking: '129',
    minor: '67',
    patch: '71',
    unknown: '82',
  },
  {
    language: 'javascript',
    item: '@types/cookie-parser',
    breaking: '34',
    minor: '49',
    patch: '132',
    unknown: '49',
  },
  {
    language: 'javascript',
    item: '@types/cors',
    breaking: '110',
    minor: '85',
    patch: '99',
    unknown: '23',
  },
  {
    language: 'javascript',
    item: 'typescript',
    breaking: '105',
    minor: '61',
    patch: '46',
    unknown: '81',
  },
  {
    language: 'javascript',
    item: '@typescript-eslint/eslint-plugin',
    breaking: '45',
    minor: '50',
    patch: '129',
    unknown: '79',
  },
  {
    language: 'javascript',
    item: '@typescript-eslint/parser',
    breaking: '122',
    minor: '142',
    patch: '68',
    unknown: '26',
  },
  {
    language: 'javascript',
    item: '@types/dotenv',
    breaking: '142',
    minor: '100',
    patch: '67',
    unknown: '146',
  },
  {
    language: 'javascript',
    item: '@types/express',
    breaking: '95',
    minor: '91',
    patch: '28',
    unknown: '58',
  },
  {
    language: 'javascript',
    item: '@types/helmet',
    breaking: '89',
    minor: '134',
    patch: '107',
    unknown: '99',
  },
  {
    language: 'javascript',
    item: '@types/hpp',
    breaking: '145',
    minor: '22',
    patch: '120',
    unknown: '27',
  },
  {
    language: 'javascript',
    item: '@types/jest',
    breaking: '91',
    minor: '73',
    patch: '85',
    unknown: '131',
  },
  {
    language: 'javascript',
    item: '@types/jsonwebtoken',
    breaking: '140',
    minor: '146',
    patch: '47',
    unknown: '120',
  },
  {
    language: 'javascript',
    item: '@types/morgan',
    breaking: '41',
    minor: '40',
    patch: '59',
    unknown: '41',
  },
  {
    language: 'javascript',
    item: '@types/node',
    breaking: '38',
    minor: '31',
    patch: '101',
    unknown: '54',
  },
  {
    language: 'javascript',
    item: '@types/supertest',
    breaking: '143',
    minor: '52',
    patch: '77',
    unknown: '122',
  },
  {
    language: 'javascript',
    item: '@types/swagger-jsdoc',
    breaking: '84',
    minor: '89',
    patch: '39',
    unknown: '141',
  },
  {
    language: 'javascript',
    item: '@types/swagger-ui-express',
    breaking: '128',
    minor: '52',
    patch: '144',
    unknown: '52',
  },
  {
    language: 'javascript',
    item: '@types/winston',
    breaking: '144',
    minor: '135',
    patch: '141',
    unknown: '112',
  },
  {
    language: 'javascript',
    item: 'winston',
    breaking: '69',
    minor: '51',
    patch: '42',
    unknown: '91',
  },
  {
    language: 'javascript',
    item: 'winston-daily-rotate-file',
    breaking: '116',
    minor: '110',
    patch: '120',
    unknown: '114',
  },
];
